### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Avocado873** [M0rica/EpicSpellsPlugin#11]
Sorry if this is a really stupid question, but how do you install the plugin?

**Comment by M0rica** [comment]
Hey, the installation is quite simple.
First, install a Spigot server on your pc, there are a lot of tutorials that explain how to set this up. Then you just head over to https://github.com/M0rica/EpicSpellsPlugin/releases and grab the .jar file from the latest release (found under "Assets"). Finally, you place this file into your servers's plugins folder and that's it! You can now start the server and use the plugin.

**Comment by Avocado873** [comment]
Thank You!
