### ISSUE TITLE
Adding spell pattern points when receiving packets from player instead of every tick

### ISSUE THREAD

**Issue by nullTheCoder** [M0rica/EpicSpellsPlugin#7]
**Is your feature request related to a problem? Please describe.**

Yes, incase of a player having packet loss some packets may arrive out of order making the server have to wait for the packets which should have arrived, during the waiting the player's head position will not be updated and when the packets in the middle finally arrive to the server the server will update player's head position to the latest one in less than a tick causing the player's head to jerk which can affect the player's ability to draw spell patterns.

an oversimplified example:

0. Player tells the server that its head is looking at (0, 0). 
1. Server receives player's head position and sets it to (0, 0).
-
2. The pattern recording code records position (0, 0)
-
3. Player tells the server that its head is looking at (0.5, 1).
4. The packet with player's position is lost.
5. The server does not get player's head position.
-
6. Player tells the server that its head is looking at (1, 0).
7. The server's computer gets player's position (1, 0).
8. The server's computer realises that it did not receive a packet which was in the middle so it does not pass the packet to the Minecraft server yet.
-
9. Player understands that the server did not get the packet.
10. Player resends the packet where its head position is (0.5, 1).
-
11. Server's computer gets the packet where players position is (0.5, 1)
12. Server's computer sends both packets in the order (0.5, 1), (1, 0) to the Minecraft server.
-
13. Server receives packet where player's head position is (0.5, 1)
14. the server sets player's position to (0.5, 1) 
15. In less than a tick after that the server receives packet where player's head position is (1, 0)
16. the server sets player's position to (1, 0)
-
17. The pattern recording code records position (1, 0)
-
18. The player instead of getting a triangle [(0, 0), (0.5, 1), (1, 0)] gets a line [(0, 0), (1, 0)]
19. The player which was unable to cast its spell dies to a zombie which the its spell was supposed to kill.

-
-
-

**Describe the solution you'd like**

Instead of recording player's position on tick record it when the Minecraft server receives player [look packet](https://wiki.vg/index.php?title=Protocol&oldid=7368#Player_Look)

-

**Describe alternatives you've considered**

Ignore this problem because it requires NMS to solve it.

**Comment by M0rica** [comment]
Thank you for reporting this problem, I wasn't aware of that! However, I want to leave NMS out of this project if possible to maintain compatibility with other Minecraft versions. Also spell patterns require a good amount of recorded points and the system _can_ correct small mistakes in some cases. So if high package loss impacts your spell casting abilities, it will probably be difficult to play on the server in general so that spell casting isn't your main issue I think. 
So I'd like to ignore this problem for now, if it becomes a bigger issue at some point I will fix it.
