### ISSUE TITLE
Requesting to make a datapack

### ISSUE THREAD

**Issue by phoenix158** [M0rica/EpicSpellsPlugin#8]
Hey M0rica can you please make a datapack with same functions or post this plugin on websites like spigot or papermc as some minecraft server hosting websites like aternos do not allow custom plugins .

**Comment by M0rica** [comment]
Hi, I will not make a datapack with the same functions, but I do plan to put this plugin on curseforge. Probably not before releasing the final version of 0.1 though.

**Comment by phoenix158** [comment]
Ok, Thanks
That will work , but please send me the link when you will upload it on the site
